# Generated by Django 4.1.7 on 2023-05-19 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('stid', models.CharField(default='', max_length=255)),
                ('stdesc', models.CharField(default='', max_length=255)),
                ('st', models.BooleanField(default=0)),
                ('listened', models.BooleanField(default=0)),
            ],
        ),
    ]
