# Generated by Django 4.1.7 on 2023-03-22 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeReadedmilsec', models.PositiveIntegerField(default=0)),
                ('timeReadedsecond', models.PositiveIntegerField(default=0)),
                ('timeReadedminute', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
